// Mocks generated by Mockito 5.4.4 from annotations
// in project/test/features/items/bloc/items_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:project/src/features/items/data/models/item.dart' as _i6;
import 'package:project/src/features/items/data/models/room.dart' as _i5;
import 'package:project/src/features/items/data/repositories/items_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRoom_0 extends _i1.SmartFake implements _i5.Room {
  _FakeRoom_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeItem_1 extends _i1.SmartFake implements _i6.Item {
  _FakeItem_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ItemsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockItemsRepository extends _i1.Mock implements _i3.ItemsRepository {
  MockItemsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.Room>> getRooms() => (super.noSuchMethod(
        Invocation.method(
          #getRooms,
          [],
        ),
        returnValue: _i4.Future<List<_i5.Room>>.value(<_i5.Room>[]),
      ) as _i4.Future<List<_i5.Room>>);

  @override
  _i4.Future<_i5.Room> addRoom({
    required String? roomName,
    required String? roomIcon,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRoom,
          [],
          {
            #roomName: roomName,
            #roomIcon: roomIcon,
          },
        ),
        returnValue: _i4.Future<_i5.Room>.value(_FakeRoom_0(
          this,
          Invocation.method(
            #addRoom,
            [],
            {
              #roomName: roomName,
              #roomIcon: roomIcon,
            },
          ),
        )),
      ) as _i4.Future<_i5.Room>);

  @override
  _i4.Future<List<_i6.Item>> getItemsInRoom(String? roomId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getItemsInRoom,
          [roomId],
        ),
        returnValue: _i4.Future<List<_i6.Item>>.value(<_i6.Item>[]),
      ) as _i4.Future<List<_i6.Item>>);

  @override
  _i4.Future<_i6.Item> addItemToRoom({
    required String? roomId,
    required String? itemName,
    required int? quantity,
    double? cost,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addItemToRoom,
          [],
          {
            #roomId: roomId,
            #itemName: itemName,
            #quantity: quantity,
            #cost: cost,
          },
        ),
        returnValue: _i4.Future<_i6.Item>.value(_FakeItem_1(
          this,
          Invocation.method(
            #addItemToRoom,
            [],
            {
              #roomId: roomId,
              #itemName: itemName,
              #quantity: quantity,
              #cost: cost,
            },
          ),
        )),
      ) as _i4.Future<_i6.Item>);
}
