// Mocks generated by Mockito 5.4.4 from annotations
// in project/test/features/auth/bloc/auth_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:project/src/features/auth/data/models/user.dart' as _i2;
import 'package:project/src/features/auth/data/repositories/auth_repository.dart'
    as _i3;
import 'package:project/src/features/family/data/models/family.dart' as _i6;
import 'package:project/src/features/family/data/repositories/family_repository.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFamily_1 extends _i1.SmartFake implements _i6.Family {
  _FakeFamily_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.User> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue: _i4.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #login,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i4.Future<_i2.User>);

  @override
  _i4.Future<_i2.User> register({
    required String? firstName,
    String? lastName,
    required String? email,
    required String? password,
    String? phoneNumber,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {
            #firstName: firstName,
            #lastName: lastName,
            #email: email,
            #password: password,
            #phoneNumber: phoneNumber,
          },
        ),
        returnValue: _i4.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #register,
            [],
            {
              #firstName: firstName,
              #lastName: lastName,
              #email: email,
              #password: password,
              #phoneNumber: phoneNumber,
            },
          ),
        )),
      ) as _i4.Future<_i2.User>);

  @override
  _i4.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.User?> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i4.Future<_i2.User?>.value(),
      ) as _i4.Future<_i2.User?>);
}

/// A class which mocks [FamilyRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFamilyRepository extends _i1.Mock implements _i5.FamilyRepository {
  MockFamilyRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i6.Family> createFamily({
    required String? familyName,
    String? familySurname,
    String? city,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createFamily,
          [],
          {
            #familyName: familyName,
            #familySurname: familySurname,
            #city: city,
          },
        ),
        returnValue: _i4.Future<_i6.Family>.value(_FakeFamily_1(
          this,
          Invocation.method(
            #createFamily,
            [],
            {
              #familyName: familyName,
              #familySurname: familySurname,
              #city: city,
            },
          ),
        )),
      ) as _i4.Future<_i6.Family>);

  @override
  _i4.Future<void> joinFamily(String? familyCode) => (super.noSuchMethod(
        Invocation.method(
          #joinFamily,
          [familyCode],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> checkUserFamilyStatus() => (super.noSuchMethod(
        Invocation.method(
          #checkUserFamilyStatus,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
