// Mocks generated by Mockito 5.4.4 from annotations
// in project/test/blocs/auth/auth_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:project/src/api/api_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _Fake_dynamic_0 extends _i1.SmartFake {
  _Fake_dynamic_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i3.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<dynamic> get(
    String? endpoint, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [endpoint],
          {#headers: headers},
        ),
        returnValue: _i4.Future<dynamic>.value(_Fake_dynamic_0(
          this,
          Invocation.method(
            #get,
            [endpoint],
            {#headers: headers},
          ),
        )),
      ) as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> post(
    String? endpoint, {
    Map<String, String>? headers,
    dynamic body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [endpoint],
          {
            #headers: headers,
            #body: body,
          },
        ),
        returnValue: _i4.Future<dynamic>.value(_Fake_dynamic_0(
          this,
          Invocation.method(
            #post,
            [endpoint],
            {
              #headers: headers,
              #body: body,
            },
          ),
        )),
      ) as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> put(
    String? endpoint, {
    Map<String, String>? headers,
    dynamic body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [endpoint],
          {
            #headers: headers,
            #body: body,
          },
        ),
        returnValue: _i4.Future<dynamic>.value(_Fake_dynamic_0(
          this,
          Invocation.method(
            #put,
            [endpoint],
            {
              #headers: headers,
              #body: body,
            },
          ),
        )),
      ) as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> delete(
    String? endpoint, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [endpoint],
          {#headers: headers},
        ),
        returnValue: _i4.Future<dynamic>.value(_Fake_dynamic_0(
          this,
          Invocation.method(
            #delete,
            [endpoint],
            {#headers: headers},
          ),
        )),
      ) as _i4.Future<dynamic>);
}
